fix: Correct a small bug
casbin/casbin-oa pull request #4
Opened 2021-07-02 15:05 UTC by MRGUOKING

Signed-off-by: MRGUOKING <420919469@qq.com>

If the oa backend can't get users from casdoor or get students correctly from database. the os frontend will wrong.Because the array is null.

Signed-off-by: MRGUOKING <420919469@qq.com>

2021-07-03 01:12 UTC, hsluoyz commented
@Kininaru plz review

2021-07-03 01:55 UTC, MRGUOKING commented
![image](https://user-images.githubusercontent.com/55344330/124340012-be7fb900-dbe4-11eb-9492-21bf764e1ed3.png)
The wrong like this

2021-07-03 03:09 UTC, hsluoyz requested changes

2021-07-03 03:09 UTC, hsluoyz commented on controllers/auth.go
> +	users, _ := auth.GetUsers()
Ignoring error is not good.

2021-07-03 04:02 UTC, Kininaru reviewed
Please don't remove the error handler in the backend. We should add a judgement here:
https://github.com/casbin/casbin-oa/blob/9162fbd3c8ad73c0b28442f0a2309ede2b4f66d5/web/src/App.js#L76

2021-07-03 05:06 UTC, MRGUOKING commented
@Kininaru I add a judgement at font end. how about this?

2021-07-03 05:23 UTC, Kininaru approved these changes

2021-07-09 09:03 UTC, hsluoyz commented
@MRGUOKING can you show error as an antd popup?

2021-07-22 15:58 UTC, closed without merging